import type { JuanPageDocument } from "../schema/page.js";

export const futureWorkspace: JuanPageDocument = {
  version: "2.0",
  title: "The Human Interface for Agentic Work",
  intent: "Build the future",
  description: "Information stays inert until an explicit semantic affordance makes it inspectable, editable, selectable, scoped, or executable.",
  theme: "dark",
  metrics: [
    { id: "objects", label: "Visible objects", operation: "count" },
    { id: "progress", label: "Execution progress", operation: "progress", field: "complete", format: "percent" },
    { id: "budget", label: "Runtime budget", operation: "sum", field: "credits", format: "number" },
  ],
  projections: [
    {
      id: "effort-by-owner",
      label: "Task effort by owner",
      sourceType: "task",
      dimension: "owner",
      operation: "sum",
      measure: "effort",
      format: "number",
    },
  ],
  objects: [
    {
      id: "north-star",
      type: "vision",
      group: "Direction",
      name: "One schema. One UI.",
      status: "Active",
      tone: "success",
      summary: "Agents describe meaning and available operations. The runtime composes the smallest truthful human surface.",
      fields: [
        { key: "principle", value: "Information + affordances + bindings", display: "prominent" },
        { key: "complete", value: true },
      ],
    },
    {
      id: "schema",
      type: "capability",
      group: "System",
      name: "JuanPage semantic graph",
      status: "Ready",
      tone: "info",
      summary: "Objects never own controls. Stable bindings connect semantic targets to shared affordances.",
      fields: [
        { key: "version", value: "2.0" },
        { key: "objectsSupported", value: "Any typed object" },
        { key: "complete", value: true },
      ],
    },
    {
      id: "runtime",
      type: "capability",
      group: "System",
      name: "Adaptive runtime",
      status: "Ready",
      tone: "info",
      summary: "Layout is a runtime decision. The schema carries meaning, not a screen or component tree.",
      fields: [
        { key: "composition", value: "Capability-aware" },
        { key: "trustedDOM", value: true },
        { key: "complete", value: true },
      ],
    },
    {
      id: "decision",
      type: "decision",
      group: "Execution",
      name: "Choose the first execution path",
      status: "Needs human",
      tone: "warning",
      summary: "Human judgment becomes typed shared state rather than a separate application flow.",
      fields: [
        { key: "priority", value: "Universal demo" },
        { key: "owner", value: "Human + agent" },
        { key: "complete", value: false },
        { key: "note", value: "" },
      ],
    },
    {
      id: "task-schema",
      type: "task",
      group: "Execution",
      name: "Define the semantic contract",
      status: "Done",
      tone: "success",
      summary: "Separate information, affordances, bindings, scope, selection, and operation receipts.",
      fields: [
        { key: "owner", value: "Agent" },
        { key: "effort", value: 3 },
        { key: "complete", value: true },
      ],
    },
    {
      id: "task-renderer",
      type: "task",
      group: "Execution",
      name: "Render one adaptive semantic surface",
      status: "In progress",
      tone: "warning",
      summary: "Controls appear only where a valid binding exists and every dependent view updates from one state transition.",
      fields: [
        { key: "owner", value: "Runtime" },
        { key: "effort", value: 5 },
        { key: "complete", value: false },
      ],
    },
    {
      id: "credits",
      type: "resource",
      group: "Resources",
      name: "Runtime compute credits",
      status: "Available",
      tone: "neutral",
      summary: "This object is display-only because it has no binding.",
      fields: [
        { key: "credits", value: 4200, format: "number", display: "prominent" },
        { key: "unit", value: "agent-seconds" },
        { key: "complete", value: false },
      ],
    },
    {
      id: "risk",
      type: "risk",
      group: "Signals",
      name: "Interface fragmentation",
      status: "Eliminated",
      tone: "success",
      summary: "A single semantic operation can be activated through a field, card, chart point, voice command, or agent call.",
      fields: [
        { key: "severity", value: "Previously high" },
        { key: "mitigation", value: "Affordances + bindings" },
        { key: "complete", value: true },
      ],
    },
  ],
  relations: [
    { id: "rel:vision-schema", from: "north-star", to: "schema", kind: "requires" },
    { id: "rel:vision-runtime", from: "north-star", to: "runtime", kind: "requires" },
    { id: "rel:schema-task", from: "schema", to: "task-schema", kind: "implemented-by" },
    { id: "rel:runtime-task", from: "runtime", to: "task-renderer", kind: "implemented-by" },
    { id: "rel:decision-task", from: "decision", to: "task-renderer", kind: "unblocks" },
    { id: "rel:credits-runtime", from: "credits", to: "runtime", kind: "powers" },
    { id: "rel:runtime-risk", from: "runtime", to: "risk", kind: "eliminates" },
  ],
  affordances: [
    { id: "inspect", label: "Inspect", effect: { kind: "inspect" }, input: { kind: "none" } },
    { id: "copy-object", label: "Copy vision", effect: { kind: "copy", source: "object" }, input: { kind: "none" } },
    {
      id: "choose-path",
      label: "Execution path",
      effect: { kind: "set", field: "priority" },
      input: {
        kind: "choice",
        options: [
          { label: "Universal demo", value: "Universal demo" },
          { label: "Agent protocol", value: "Agent protocol" },
          { label: "Remote documents", value: "Remote documents" },
        ],
      },
    },
    { id: "approve-decision", label: "Approved", tone: "success", effect: { kind: "set", field: "complete" }, input: { kind: "boolean" } },
    { id: "decision-note", label: "Human context", effect: { kind: "set", field: "note" }, input: { kind: "text", placeholder: "Tell the next agent what matters", multiline: true } },
    { id: "toggle-task", label: "Complete", effect: { kind: "set", field: "complete" }, input: { kind: "boolean" } },
    { id: "renderer-effort", label: "Effort", effect: { kind: "set", field: "effort" }, input: { kind: "number", min: 0, max: 20, step: 1, presentation: "adjust" } },
    { id: "select-task", label: "Select task", effect: { kind: "select", selection: "tasks", mode: "multiple" }, input: { kind: "none" } },
  ],
  bindings: [
    { id: "bind:inspect-schema", target: { kind: "object", object: "schema" }, affordance: "inspect" },
    { id: "bind:inspect-runtime", target: { kind: "object", object: "runtime" }, affordance: "inspect" },
    { id: "bind:inspect-decision", target: { kind: "object", object: "decision" }, affordance: "inspect" },
    { id: "bind:copy-vision", target: { kind: "object", object: "north-star" }, affordance: "copy-object" },
    { id: "bind:path", target: { kind: "field", object: "decision", field: "priority" }, affordance: "choose-path" },
    { id: "bind:approve", target: { kind: "field", object: "decision", field: "complete" }, affordance: "approve-decision" },
    { id: "bind:note", target: { kind: "field", object: "decision", field: "note" }, affordance: "decision-note" },
    { id: "bind:task-schema-complete", target: { kind: "field", object: "task-schema", field: "complete" }, affordance: "toggle-task" },
    { id: "bind:task-renderer-complete", target: { kind: "field", object: "task-renderer", field: "complete" }, affordance: "toggle-task" },
    { id: "bind:task-renderer-effort", target: { kind: "field", object: "task-renderer", field: "effort" }, affordance: "renderer-effort" },
    { id: "bind:select-schema-task", target: { kind: "object", object: "task-schema" }, affordance: "select-task" },
    { id: "bind:select-renderer-task", target: { kind: "object", object: "task-renderer" }, affordance: "select-task" },
  ],
};
