import type { JuanPagerDocument } from "../schema/document.js";

/** Sample grocery plan. Prices are labeled samples — not live store prices. */
export const groceryPlan: JuanPagerDocument = {
  version: "0.1",
  title: "Justin’s Four-Day Grocery Plan",
  description:
    "A compact high-protein shopping plan for four days. Sample prices only — not current store prices.",
  theme: "system",
  metadata: {
    days: 4,
    audience: "demo",
    priceNote: "sample",
  },
  components: [
    {
      type: "summary",
      id: "plan-summary",
      items: [
        { label: "Estimated total", value: "$63.42 (sample)" },
        { label: "Daily protein target", value: "160g+" },
        { label: "Stores", value: "ALDI · Costco · Trader Joe’s" },
        { label: "Days covered", value: "4" },
      ],
    },
    {
      type: "text",
      text: "Check items as you shop. Quantities and purchased state stay on this device only.",
    },
    {
      type: "grid",
      columns: 2,
      components: [
        {
          type: "button",
          label: "Copy shopping list",
          action: "copy-list",
          variant: "primary",
        },
        {
          type: "button",
          label: "Print page",
          action: "print-page",
          variant: "secondary",
        },
        {
          type: "button",
          label: "Reset local changes",
          action: "reset-state",
          variant: "danger",
        },
        {
          type: "button",
          label: "Copy page link",
          action: "copy-page",
          variant: "secondary",
        },
      ],
    },
    {
      type: "section",
      id: "protein",
      title: "Protein staples",
      collapsible: true,
      components: [
        {
          type: "grid",
          columns: 2,
          components: [
            {
              type: "product",
              id: "chicken-breast",
              name: "Chicken Breast",
              store: "ALDI",
              imageUrl: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=640&q=80",
              displayPrice: "$11.42",
              price: 11.42,
              currency: "USD",
              unitPrice: "$3.81 / lb",
              packageSize: "3 lb tray",
              quantity: 1,
              availability: "in-stock",
              productUrl: "https://www.aldi.us/",
              reason: "Lean protein base for lunches and dinners across four days.",
              badges: ["High protein", "Sample price"],
              checked: false,
            },
            {
              type: "product",
              id: "greek-yogurt",
              name: "Plain Greek Yogurt",
              store: "Costco",
              imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=640&q=80",
              displayPrice: "$5.99",
              price: 5.99,
              currency: "USD",
              unitPrice: "$0.19 / oz",
              packageSize: "32 oz tub",
              quantity: 2,
              availability: "in-stock",
              productUrl: "https://www.costco.com/",
              reason: "Quick breakfast protein with fruit or honey.",
              badges: ["Breakfast", "Sample price"],
            },
            {
              type: "product",
              id: "eggs",
              name: "Large Eggs",
              store: "ALDI",
              imageUrl: "https://images.unsplash.com/photo-1518569656558-1f25e69d93d7?w=640&q=80",
              displayPrice: "$3.48",
              price: 3.48,
              currency: "USD",
              unitPrice: "$0.29 / egg",
              packageSize: "12 count",
              quantity: 1,
              availability: "limited",
              productUrl: "https://www.aldi.us/",
              reason: "Cheap complete protein for breakfast and snacks.",
              badges: ["Staple", "Sample price"],
            },
          ],
        },
      ],
    },
    {
      type: "section",
      id: "produce",
      title: "Produce & sides",
      collapsible: true,
      components: [
        {
          type: "grid",
          columns: 2,
          components: [
            {
              type: "product",
              id: "spinach",
              name: "Baby Spinach",
              store: "Trader Joe’s",
              imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=640&q=80",
              displayPrice: "$2.49",
              price: 2.49,
              currency: "USD",
              unitPrice: "$0.42 / oz",
              packageSize: "6 oz bag",
              quantity: 2,
              availability: "in-stock",
              productUrl: "https://www.traderjoes.com/",
              reason: "Volume vegetable for omelets, bowls, and sides.",
              badges: ["Produce", "Sample price"],
            },
            {
              type: "product",
              id: "bananas",
              name: "Bananas",
              store: "ALDI",
              imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=640&q=80",
              displayPrice: "$1.39",
              price: 1.39,
              currency: "USD",
              unitPrice: "$0.55 / lb",
              packageSize: "bunch (~2.5 lb)",
              quantity: 1,
              availability: "in-stock",
              productUrl: "https://www.aldi.us/",
              reason: "Portable carbs to pair with yogurt and post-workout snacks.",
              badges: ["Produce", "Sample price"],
            },
            {
              type: "product",
              id: "rice",
              name: "Jasmine Rice",
              store: "Costco",
              imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=640&q=80",
              displayPrice: "$12.99",
              price: 12.99,
              currency: "USD",
              unitPrice: "$0.54 / lb",
              packageSize: "25 lb bag",
              quantity: 1,
              availability: "in-stock",
              productUrl: "https://www.costco.com/",
              reason: "Bulk carb base; leftover bag covers future weeks.",
              badges: ["Bulk", "Sample price"],
            },
          ],
        },
      ],
    },
    {
      type: "section",
      id: "extras",
      title: "Pantry extras",
      collapsible: true,
      collapsed: true,
      components: [
        {
          type: "product",
          id: "olive-oil",
          name: "Extra Virgin Olive Oil",
          store: "Trader Joe’s",
          imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=640&q=80",
          displayPrice: "$8.99",
          price: 8.99,
          currency: "USD",
          unitPrice: "$0.53 / fl oz",
          packageSize: "16.9 fl oz",
          quantity: 1,
          availability: "unknown",
          productUrl: "https://www.traderjoes.com/",
          reason: "Cooking fat for chicken and vegetables.",
          badges: ["Pantry", "Sample price"],
        },
        {
          type: "list",
          ordered: false,
          items: [
            "Batch-cook chicken on day one",
            "Pair yogurt + fruit each morning",
            "Use spinach across eggs and bowls",
          ],
        },
      ],
    },
    {
      type: "divider",
    },
    {
      type: "text",
      text: "Prices shown are clearly labeled samples for the JuanPager demo and may not match current store pricing.",
    },
  ],
};

export default groceryPlan;
