import type { JuanPageDocument } from "../schema/page.js";

export const juanPageStudio: JuanPageDocument = {
  version: "2.0",
  title: "JuanPage Studio",
  intent: "Turn an ordinary user request into one validated, hosted JuanPage experience.",
  description: "A human and ChatGPT share typed state for defining a page request, choosing the delivery contract, reviewing guardrails, and proposing generation through the trusted runtime.",
  theme: "dark",
  metrics: [
    { id: "studio-objects", label: "Semantic objects", operation: "count", format: "number" },
    { id: "studio-progress", label: "Studio progress", operation: "progress", field: "complete", format: "percent" },
    { id: "studio-effort", label: "Planned effort", operation: "sum", field: "effort", format: "number" },
  ],
  scopes: [
    { id: "owner-scope", label: "Work owner", field: "owner", initial: null, objectTypes: ["task"] },
  ],
  projections: [
    {
      id: "effort-by-owner",
      label: "Effort by owner",
      sourceType: "task",
      dimension: "owner",
      operation: "sum",
      measure: "effort",
      format: "number",
    },
  ],
  objects: [
    {
      id: "skill-contract",
      type: "skill",
      group: "JuanPage",
      name: "JuanPage",
      status: "Ready",
      tone: "success",
      summary: "The single user-facing skill that converts a request into a validated JuanPage URL or an M1 round-trip session.",
      tags: ["JuanPage 2.0", "User-facing", "Hosted"],
      fields: [
        { key: "skillName", label: "Skill name", value: "juanpage", display: "prominent" },
        { key: "purpose", label: "Purpose", value: "Generate hosted JuanPages and typed human handoffs from ordinary requests." },
        { key: "mode", label: "Default mode", value: "Generate a working URL" },
        { key: "complete", label: "JuanPage ready", value: true },
      ],
    },
    {
      id: "generation-brief",
      type: "brief",
      group: "Request",
      name: "Page generation brief",
      status: "Needs review",
      tone: "info",
      summary: "The user describes the desired world. JuanPage translates it into semantic objects, operations, state, and authority.",
      fields: [
        {
          key: "scenario",
          label: "Scenario",
          value: "Create a product launch command center with workstream filters, completion checklists, and a clear launch owner.",
          display: "prominent",
        },
        { key: "audience", label: "Audience", value: "End users" },
        { key: "delivery", label: "Delivery", value: "Hosted JuanPage URL" },
        { key: "handoffMode", label: "Human handoff", value: "Local typed state" },
        { key: "complete", label: "Brief approved", value: false },
      ],
    },
    {
      id: "generated-page",
      type: "artifact",
      group: "Result",
      name: "Hosted JuanPage result",
      status: "Pending",
      tone: "warning",
      summary: "The final page is data transported to the trusted renderPage runtime, not a generated application or second UI schema.",
      fields: [
        { key: "contract", label: "Contract", value: "JuanPage 2.0", display: "prominent" },
        { key: "host", label: "JuanPager host", value: "https://cakerepository.github.io/JuanPage/", format: "url" },
        { key: "renderer", label: "Renderer", value: "renderPage" },
        { key: "complete", label: "Generated and decoded", value: false },
      ],
    },
    {
      id: "guardrail-schema",
      type: "guardrail",
      group: "Guardrails",
      name: "Strict schema validation",
      status: "Required",
      tone: "success",
      summary: "Every object, effect, input, binding, and reference must pass the live validatePage path.",
      fields: [
        { key: "rule", value: "Source and executable tests outrank remembered examples." },
        { key: "complete", value: true },
      ],
    },
    {
      id: "guardrail-interactions",
      type: "guardrail",
      group: "Guardrails",
      name: "Interaction truth",
      status: "Required",
      tone: "success",
      summary: "Nothing looks interactive unless an affordance and binding produce typed state, a delta, or a receipt.",
      fields: [
        { key: "rule", value: "No decorative controls or fake clickable surfaces." },
        { key: "complete", value: true },
      ],
    },
    {
      id: "guardrail-authority",
      type: "guardrail",
      group: "Guardrails",
      name: "Trusted execution boundary",
      status: "Required",
      tone: "success",
      summary: "Self-contained URLs are record-only for remote effects; trusted hosts retain authorization and idempotency.",
      fields: [
        { key: "rule", value: "Invoke never becomes arbitrary executable page content." },
        { key: "complete", value: true },
      ],
    },
    {
      id: "task-model",
      type: "task",
      group: "Workflow",
      name: "Model the semantic page",
      status: "Done",
      tone: "success",
      summary: "Translate the request into objects, fields, relations, affordances, bindings, state, and authority.",
      fields: [
        { key: "owner", value: "Agent" },
        { key: "effort", value: 3 },
        { key: "complete", value: true },
      ],
    },
    {
      id: "task-validate",
      type: "task",
      group: "Workflow",
      name: "Validate and round-trip the page",
      status: "In progress",
      tone: "warning",
      summary: "Run validatePage, encode the v5 URL, and decode it back to the same semantic document.",
      fields: [
        { key: "owner", value: "Runtime" },
        { key: "effort", value: 2 },
        { key: "complete", value: false },
      ],
    },
    {
      id: "task-review",
      type: "task",
      group: "Workflow",
      name: "Approve the hosted result",
      status: "Needs human",
      tone: "warning",
      summary: "Human review becomes typed shared state before the generated URL is accepted as the result.",
      fields: [
        { key: "owner", value: "Human" },
        { key: "effort", value: 1 },
        { key: "complete", value: false },
      ],
    },
  ],
  relations: [
    { id: "rel-skill-brief", from: "skill-contract", to: "generation-brief", kind: "translates" },
    { id: "rel-skill-output", from: "skill-contract", to: "generated-page", kind: "generates" },
    { id: "rel-output-schema", from: "generated-page", to: "guardrail-schema", kind: "validated-by" },
    { id: "rel-output-interactions", from: "generated-page", to: "guardrail-interactions", kind: "constrained-by" },
    { id: "rel-output-authority", from: "generated-page", to: "guardrail-authority", kind: "constrained-by" },
    { id: "rel-skill-model", from: "skill-contract", to: "task-model", kind: "implemented-by" },
    { id: "rel-model-validate", from: "task-model", to: "task-validate", kind: "precedes" },
    { id: "rel-validate-review", from: "task-validate", to: "task-review", kind: "precedes" },
  ],
  affordances: [
    { id: "inspect", label: "Inspect", effect: { kind: "inspect" }, input: { kind: "none" } },
    { id: "copy-juanpage", label: "Copy JuanPage contract", effect: { kind: "copy", source: "object" }, input: { kind: "none" } },
    {
      id: "edit-scenario",
      label: "Scenario",
      effect: { kind: "set", field: "scenario" },
      input: { kind: "text", placeholder: "Describe the human outcome and real operations", multiline: true },
    },
    {
      id: "choose-audience",
      label: "Audience",
      effect: { kind: "set", field: "audience" },
      input: {
        kind: "choice",
        options: [
          { label: "End users", value: "End users" },
          { label: "Product teams", value: "Product teams" },
          { label: "Protocol builders", value: "Protocol builders" },
        ],
      },
    },
    {
      id: "choose-delivery",
      label: "Delivery",
      effect: { kind: "set", field: "delivery" },
      input: {
        kind: "choice",
        options: [
          { label: "Hosted JuanPage URL", value: "Hosted JuanPage URL" },
          { label: "JuanPage JSON", value: "JuanPage JSON" },
          { label: "M1 round-trip session", value: "M1 round-trip session" },
        ],
      },
    },
    {
      id: "choose-handoff",
      label: "Human handoff",
      effect: { kind: "set", field: "handoffMode" },
      input: {
        kind: "choice",
        options: [
          { label: "Local typed state", value: "Local typed state" },
          { label: "Return deltas and receipts", value: "Return deltas and receipts" },
        ],
      },
    },
    {
      id: "edit-host",
      label: "JuanPager host",
      effect: { kind: "set", field: "host" },
      input: { kind: "text", placeholder: "https://host.example/JuanPage/" },
    },
    { id: "toggle-complete", label: "Complete", effect: { kind: "set", field: "complete" }, input: { kind: "boolean" } },
    {
      id: "scope-owner",
      label: "Work owner",
      effect: { kind: "scope", scope: "owner-scope" },
      input: {
        kind: "choice",
        options: [
          { label: "All owners", value: null },
          { label: "Agent", value: "Agent" },
          { label: "Runtime", value: "Runtime" },
          { label: "Human", value: "Human" },
        ],
      },
    },
    { id: "select-task", label: "Select task", effect: { kind: "select", selection: "studio-tasks", mode: "multiple" }, input: { kind: "none" } },
    {
      id: "generate-page",
      label: "Generate hosted page",
      description: "Propose URL generation through JuanPage after human review.",
      tone: "primary",
      effect: { kind: "invoke", operation: "generate-hosted-juanpage", policy: "approval" },
      input: { kind: "none" },
    },
  ],
  bindings: [
    { id: "bind-inspect-skill", target: { kind: "object", object: "skill-contract" }, affordance: "inspect" },
    { id: "bind-inspect-output", target: { kind: "object", object: "generated-page" }, affordance: "inspect" },
    { id: "bind-inspect-schema", target: { kind: "object", object: "guardrail-schema" }, affordance: "inspect" },
    { id: "bind-inspect-interactions", target: { kind: "object", object: "guardrail-interactions" }, affordance: "inspect" },
    { id: "bind-inspect-authority", target: { kind: "object", object: "guardrail-authority" }, affordance: "inspect" },
    { id: "bind-copy-juanpage", target: { kind: "object", object: "skill-contract" }, affordance: "copy-juanpage" },
    { id: "bind-scenario", target: { kind: "field", object: "generation-brief", field: "scenario" }, affordance: "edit-scenario" },
    { id: "bind-audience", target: { kind: "field", object: "generation-brief", field: "audience" }, affordance: "choose-audience" },
    { id: "bind-delivery", target: { kind: "field", object: "generation-brief", field: "delivery" }, affordance: "choose-delivery" },
    { id: "bind-handoff", target: { kind: "field", object: "generation-brief", field: "handoffMode" }, affordance: "choose-handoff" },
    { id: "bind-host", target: { kind: "field", object: "generated-page", field: "host" }, affordance: "edit-host" },
    { id: "bind-brief-complete", target: { kind: "field", object: "generation-brief", field: "complete" }, affordance: "toggle-complete" },
    { id: "bind-output-complete", target: { kind: "field", object: "generated-page", field: "complete" }, affordance: "toggle-complete" },
    { id: "bind-task-model-complete", target: { kind: "field", object: "task-model", field: "complete" }, affordance: "toggle-complete" },
    { id: "bind-task-validate-complete", target: { kind: "field", object: "task-validate", field: "complete" }, affordance: "toggle-complete" },
    { id: "bind-task-review-complete", target: { kind: "field", object: "task-review", field: "complete" }, affordance: "toggle-complete" },
    { id: "bind-owner-scope", target: { kind: "page" }, affordance: "scope-owner", priority: "secondary" },
    { id: "bind-select-model", target: { kind: "object", object: "task-model" }, affordance: "select-task" },
    { id: "bind-select-validate", target: { kind: "object", object: "task-validate" }, affordance: "select-task" },
    { id: "bind-select-review", target: { kind: "object", object: "task-review" }, affordance: "select-task" },
    { id: "bind-generate", target: { kind: "page" }, affordance: "generate-page", priority: "primary" },
  ],
  metadata: {
    "example.kind": "juanpage-studio",
    "example.generatedBy": "juanpage",
  },
};
