import { MeaningActionKind, MeaningOpcode, meaningRef, type MeaningPacket } from "../protocol/meaning.js";

const r = meaningRef;

export const maintenanceWindowPacket: MeaningPacket = [
  1,
  "pkt:demo:maintenance-window",
  1,
  "vocab:maintenance:en",
  [
    ["txt:title", "Endpoint Maintenance Window"],
    ["txt:intent", "Review evidence, choose holdbacks, and propose a safe rollout"],
    ["txt:description", "A synthetic RMM maintenance plan transported through M1. Local human changes become typed state; production approval remains a record-only proposal for a trusted host executor."],
    ["type:endpoint", "Endpoint"],
    ["type:plan", "Maintenance plan"],
    ["txt:endpoints", "Endpoints"],
    ["txt:plan", "Plan"],
    ["txt:ready", "Ready"],
    ["txt:watch", "Watch"],
    ["txt:blocked", "Blocked"],
    ["txt:pending", "Pending approval"],
    ["txt:minneapolis", "Minneapolis"],
    ["txt:burnsville", "Burnsville"],
    ["txt:server-01", "server-01"],
    ["txt:server-01-summary", "Primary application server with current backups and no active alerts."],
    ["txt:workstation-14", "workstation-14"],
    ["txt:workstation-14-summary", "Accounting workstation with an open disk-health warning."],
    ["txt:laptop-22", "laptop-22"],
    ["txt:laptop-22-summary", "Remote laptop currently offline and excluded from automatic execution."],
    ["txt:window", "Saturday maintenance window"],
    ["txt:window-summary", "Install approved operating-system updates after backups and health checks complete."],
    ["txt:site", "Site"],
    ["txt:health", "Health score"],
    ["txt:last-backup", "Last backup"],
    ["txt:online", "Online"],
    ["txt:note", "Engineer note"],
    ["txt:scope-site", "Scope by site"],
    ["txt:all-sites", "All sites"],
    ["txt:select-holdback", "Toggle holdback selection"],
    ["txt:inspect", "Inspect evidence"],
    ["txt:add-note", "Add change note"],
    ["txt:note-placeholder", "Explain risk, exclusions, or operator context"],
    ["txt:approve", "Propose rollout approval"],
    ["txt:approve-description", "Records an approval proposal and receipt. Browser rendering never executes endpoint updates."],
    ["txt:approval-policy", "Production rollout requires explicit human approval and trusted host-side execution."],
    ["txt:evidence-source", "RMM health service"],
    ["txt:evidence-claim", "Backups are current and the ready endpoints passed preflight checks."],
    ["txt:approval-signal", "The maintenance plan is waiting for human approval."],
  ],
  [
    [MeaningOpcode.Header, r("txt:title"), r("txt:intent"), r("txt:description"), 0, 0, 0, 0],

    [MeaningOpcode.Entity, "e:server-01", "type:endpoint", r("txt:server-01"), r("txt:endpoints"), r("txt:ready"), 2, r("txt:server-01-summary"), ["a:inspect", "a:holdback"], []],
    [MeaningOpcode.Entity, "e:workstation-14", "type:endpoint", r("txt:workstation-14"), r("txt:endpoints"), r("txt:watch"), 3, r("txt:workstation-14-summary"), ["a:inspect", "a:holdback"], []],
    [MeaningOpcode.Entity, "e:laptop-22", "type:endpoint", r("txt:laptop-22"), r("txt:endpoints"), r("txt:blocked"), 4, r("txt:laptop-22-summary"), ["a:inspect", "a:holdback"], []],
    [MeaningOpcode.Entity, "e:window", "type:plan", r("txt:window"), r("txt:plan"), r("txt:pending"), 3, r("txt:window-summary"), ["a:note", "a:approve"], []],

    [MeaningOpcode.Fact, "e:server-01", "prop:site", "Minneapolis", r("txt:site"), 1, 1, null],
    [MeaningOpcode.Fact, "e:server-01", "prop:health", 0.98, r("txt:health"), 4, 1, null],
    [MeaningOpcode.Fact, "e:server-01", "prop:last-backup", "2026-08-01T03:15:00.000Z", r("txt:last-backup"), 7, 0, null],
    [MeaningOpcode.Fact, "e:server-01", "prop:online", true, r("txt:online"), 0, 0, null],

    [MeaningOpcode.Fact, "e:workstation-14", "prop:site", "Burnsville", r("txt:site"), 1, 1, null],
    [MeaningOpcode.Fact, "e:workstation-14", "prop:health", 0.72, r("txt:health"), 4, 1, null],
    [MeaningOpcode.Fact, "e:workstation-14", "prop:last-backup", "2026-08-01T02:48:00.000Z", r("txt:last-backup"), 7, 0, null],
    [MeaningOpcode.Fact, "e:workstation-14", "prop:online", true, r("txt:online"), 0, 0, null],

    [MeaningOpcode.Fact, "e:laptop-22", "prop:site", "Burnsville", r("txt:site"), 1, 1, null],
    [MeaningOpcode.Fact, "e:laptop-22", "prop:health", 0.41, r("txt:health"), 4, 1, null],
    [MeaningOpcode.Fact, "e:laptop-22", "prop:last-backup", "2026-07-29T18:05:00.000Z", r("txt:last-backup"), 7, 0, null],
    [MeaningOpcode.Fact, "e:laptop-22", "prop:online", false, r("txt:online"), 0, 0, null],

    [MeaningOpcode.Fact, "e:window", "prop:note", "Hold offline or unhealthy endpoints until an engineer reviews them.", r("txt:note"), 1, 2, null],

    [MeaningOpcode.Action, "a:site", MeaningActionKind.ScopeChoice, r("txt:scope-site"), "page", "prop:site", [null, [[r("txt:all-sites"), null], [r("txt:minneapolis"), "Minneapolis"], [r("txt:burnsville"), "Burnsville"]], "prop:site"], 0, null, null],
    [MeaningOpcode.Action, "a:holdback", MeaningActionKind.Select, r("txt:select-holdback"), null, "selection:holdbacks", ["multiple"], 0, null, null],
    [MeaningOpcode.Action, "a:inspect", MeaningActionKind.Inspect, r("txt:inspect"), null, null, null, 0, null, null],
    [MeaningOpcode.Action, "a:note", MeaningActionKind.Text, r("txt:add-note"), "e:window", "prop:note", ["Hold offline or unhealthy endpoints until an engineer reviews them.", r("txt:note-placeholder"), true], 0, null, "op:maintenance.note"],
    [MeaningOpcode.Action, "a:approve", MeaningActionKind.Emit, r("txt:approve"), "e:window", null, ["e:window"], 3, r("txt:approve-description"), "op:maintenance.approve"],

    [MeaningOpcode.Signal, "s:approval", "e:window", 0.78, r("txt:approval-signal"), 0.99, r("txt:evidence-source"), "2026-08-01T04:30:00.000Z"],
    [MeaningOpcode.Evidence, "ev:preflight", "e:window", r("txt:evidence-source"), r("txt:evidence-claim"), 0.97, "2026-08-01T04:25:00.000Z"],
    [MeaningOpcode.Permission, "a:approve", 2, r("txt:approval-policy")],
  ],
];
