import { MeaningOpcode, meaningRef, type MeaningPacket } from "../protocol/meaning.js";

const r = meaningRef;

export const futureMeaningPacket: MeaningPacket = [
  1,
  "pkt:juan:future",
  4,
  "vocab:juan:en",
  [
    ["txt:title", "Meaning is the Interface"],
    ["txt:intent", "Move meaning, not screens"],
    ["txt:description", "The agent sends opaque symbols, typed facts, relationships, signals, evidence, permissions, and actions. JuanPager creates the human projection at runtime."],
    ["type:principle", "Principle"],
    ["type:transport", "Transport"],
    ["type:decision", "Decision"],
    ["type:renderer", "Renderer"],
    ["txt:direction", "Direction"],
    ["txt:system", "System"],
    ["txt:execution", "Execution"],
    ["txt:active", "Active"],
    ["txt:ready", "Ready"],
    ["txt:human", "Needs human"],
    ["txt:north", "Shared semantic state"],
    ["txt:north-summary", "The durable product is a shared model of reality. Chat, cards, tables, voice, and future surfaces are temporary projections."],
    ["txt:packet", "M1 meaning packet"],
    ["txt:packet-summary", "Numeric opcodes and stable symbols carry structure without requiring English field names."],
    ["txt:renderer", "Capability-negotiated projection"],
    ["txt:renderer-summary", "The runtime selects a supported lens and translates vocabulary only at the human boundary."],
    ["txt:decision", "Choose the execution path"],
    ["txt:decision-summary", "Human judgment becomes a typed fact delta instead of a sentence that another agent must reinterpret."],
    ["txt:approved", "Approved"],
    ["txt:note", "Human context"],
    ["txt:approve", "Approve decision"],
    ["txt:add-note", "Add context"],
    ["txt:placeholder", "State what the next agent must preserve"],
    ["txt:signal", "Human approval is blocking execution"],
    ["txt:source", "M1 policy engine"],
    ["txt:evidence", "The decision has an explicit approval action and no approved fact."],
    ["txt:permission", "This state transition requires human approval."],
    ["rel:projects", "projects"],
    ["rel:blocks", "blocks"],
  ],
  [
    [MeaningOpcode.Header, r("txt:title"), r("txt:intent"), r("txt:description"), 2, 0, 0, 0],
    [MeaningOpcode.Entity, "e:north", "type:principle", r("txt:north"), r("txt:direction"), r("txt:active"), 2, r("txt:north-summary"), [], []],
    [MeaningOpcode.Entity, "e:packet", "type:transport", r("txt:packet"), r("txt:system"), r("txt:ready"), 1, r("txt:packet-summary"), [], []],
    [MeaningOpcode.Entity, "e:renderer", "type:renderer", r("txt:renderer"), r("txt:system"), r("txt:ready"), 1, r("txt:renderer-summary"), [], []],
    [MeaningOpcode.Entity, "e:decision", "type:decision", r("txt:decision"), r("txt:execution"), r("txt:human"), 3, r("txt:decision-summary"), ["a:approve", "a:note"], []],
    [MeaningOpcode.Fact, "e:decision", "prop:approved", false, r("txt:approved"), 0, 1, null],
    [MeaningOpcode.Fact, "e:decision", "prop:note", "", r("txt:note"), 1, 2, null],
    [MeaningOpcode.Relation, "e:north", "e:packet", "rel:projects", null],
    [MeaningOpcode.Relation, "e:packet", "e:renderer", "rel:projects", null],
    [MeaningOpcode.Relation, "e:decision", "e:renderer", "rel:blocks", null],
    [MeaningOpcode.Action, "a:approve", 0, r("txt:approve"), "e:decision", "prop:approved", false, 2, null, "act:approve"],
    [MeaningOpcode.Action, "a:note", 3, r("txt:add-note"), "e:decision", "prop:note", ["", r("txt:placeholder"), true], 0, null, "act:annotate"],
    [MeaningOpcode.Signal, "s:approval", "e:decision", 0.88, r("txt:signal"), 0.97, r("txt:source"), "2026-07-31T20:30:00.000Z"],
    [MeaningOpcode.Evidence, "ev:approval", "e:decision", r("txt:source"), r("txt:evidence"), 1, "2026-07-31T20:30:00.000Z"],
    [MeaningOpcode.Permission, "a:approve", 2, r("txt:permission")],
  ],
];
