import { MeaningActionKind, MeaningOpcode, meaningRef, type MeaningPacket } from "../protocol/meaning.js";

const r = meaningRef;

export const operationsControlRoomPacket: MeaningPacket = [
  1,
  "pkt:demo:operations",
  12,
  "vocab:demo:en",
  [
    ["txt:title", "Northstar Operations Control Room"],
    ["txt:intent", "See what needs attention, decide safely, and leave a typed audit trail"],
    ["txt:description", "Synthetic demo data for a managed service operation. Every card, relationship, edit, approval, and receipt comes from one M1 packet compiled into JuanPage 1.0."],
    ["type:customer", "Customer"],
    ["type:deployment", "Deployment"],
    ["type:incident", "Incident"],
    ["type:service", "Service"],
    ["txt:customers", "Customers"],
    ["txt:delivery", "Delivery"],
    ["txt:operations", "Operations"],
    ["txt:healthy", "Healthy"],
    ["txt:watch", "Watch"],
    ["txt:blocked", "Blocked"],
    ["txt:ready", "Ready"],
    ["txt:running", "Running"],
    ["txt:acme", "Acme Manufacturing"],
    ["txt:acme-summary", "Production customer with 248 managed endpoints across three sites."],
    ["txt:brightline", "Brightline Logistics"],
    ["txt:brightline-summary", "Pilot customer evaluating AI-assisted dispatch and endpoint operations."],
    ["txt:release", "Agent 2.4 rollout"],
    ["txt:release-summary", "Ring-based deployment is staged and waiting for a human production decision."],
    ["txt:incident", "Exchange mailbox provisioning delay"],
    ["txt:incident-summary", "Microsoft is running a backend resync. Customer impact is limited to one new mailbox."],
    ["txt:service", "Remote execution service"],
    ["txt:service-summary", "Command routing and receipt collection are healthy across all active regions."],
    ["txt:endpoints", "Managed endpoints"],
    ["txt:sites", "Sites"],
    ["txt:mrr", "Monthly recurring revenue"],
    ["txt:pilot-users", "Pilot users"],
    ["txt:success-rate", "Success rate"],
    ["txt:queued", "Queued devices"],
    ["txt:owner", "Owner"],
    ["txt:eta", "Expected update"],
    ["txt:commands", "Commands today"],
    ["txt:p95", "P95 execution time"],
    ["txt:approved", "Production approved"],
    ["txt:note", "Operator note"],
    ["txt:ring", "Deployment ring"],
    ["txt:approve", "Approve production rollout"],
    ["txt:approve-description", "Creates a proposal and receipt. It does not silently execute production changes."],
    ["txt:add-note", "Add operator context"],
    ["txt:note-placeholder", "Record what the next human or agent must know"],
    ["txt:set-ring", "Choose rollout ring"],
    ["txt:ring-pilot", "Pilot only"],
    ["txt:ring-broad", "Broad"],
    ["txt:ring-production", "Production"],
    ["txt:retry", "Retry mailbox check"],
    ["txt:retry-description", "Runs a safe diagnostic and returns a typed action receipt."],
    ["txt:delete", "Delete incident history"],
    ["txt:approval-signal", "Production rollout is waiting for human approval"],
    ["txt:incident-signal", "Mailbox update is overdue by 42 minutes"],
    ["txt:policy-engine", "Northstar policy engine"],
    ["txt:monitor", "Synthetic monitoring"],
    ["txt:release-evidence", "Pilot ring completed on 24 of 24 endpoints with no failed health checks."],
    ["txt:incident-evidence", "Microsoft support confirmed a backend Exchange resync is in progress."],
    ["txt:approve-policy", "Production changes require an explicit human proposal."],
    ["txt:retry-policy", "Read-only diagnostics may execute without additional approval."],
    ["txt:delete-policy", "Operational history is immutable in this workspace."],
    ["rel:owns", "owns"],
    ["rel:affects", "affects"],
    ["rel:depends", "depends on"],
  ],
  [
    [MeaningOpcode.Header, r("txt:title"), r("txt:intent"), r("txt:description"), 2, 0, 0, 0],

    [MeaningOpcode.Entity, "e:acme", "type:customer", r("txt:acme"), r("txt:customers"), r("txt:healthy"), 2, r("txt:acme-summary"), [], []],
    [MeaningOpcode.Entity, "e:brightline", "type:customer", r("txt:brightline"), r("txt:customers"), r("txt:watch"), 1, r("txt:brightline-summary"), [], []],
    [MeaningOpcode.Entity, "e:release", "type:deployment", r("txt:release"), r("txt:delivery"), r("txt:ready"), 3, r("txt:release-summary"), ["a:approve", "a:ring", "a:note"], []],
    [MeaningOpcode.Entity, "e:incident", "type:incident", r("txt:incident"), r("txt:operations"), r("txt:blocked"), 4, r("txt:incident-summary"), ["a:retry", "a:delete"], []],
    [MeaningOpcode.Entity, "e:remote", "type:service", r("txt:service"), r("txt:operations"), r("txt:running"), 2, r("txt:service-summary"), [], []],

    [MeaningOpcode.Fact, "e:acme", "prop:endpoints", 248, r("txt:endpoints"), 2, 1, null],
    [MeaningOpcode.Fact, "e:acme", "prop:sites", 3, r("txt:sites"), 2, 0, null],
    [MeaningOpcode.Fact, "e:acme", "prop:mrr", 6800, r("txt:mrr"), 3, 1, "USD"],
    [MeaningOpcode.Fact, "e:brightline", "prop:pilot-users", 18, r("txt:pilot-users"), 2, 1, null],
    [MeaningOpcode.Fact, "e:brightline", "prop:success-rate", 0.94, r("txt:success-rate"), 4, 1, null],
    [MeaningOpcode.Fact, "e:release", "prop:approved", false, r("txt:approved"), 0, 1, null],
    [MeaningOpcode.Fact, "e:release", "prop:ring", "pilot", r("txt:ring"), 1, 1, null],
    [MeaningOpcode.Fact, "e:release", "prop:queued", 224, r("txt:queued"), 2, 1, null],
    [MeaningOpcode.Fact, "e:release", "prop:note", "Pilot checks are clean. Waiting for production approval.", r("txt:note"), 1, 2, null],
    [MeaningOpcode.Fact, "e:incident", "prop:owner", "Microsoft Support", r("txt:owner"), 1, 1, null],
    [MeaningOpcode.Fact, "e:incident", "prop:eta", "2026-07-31T22:30:00.000Z", r("txt:eta"), 7, 1, null],
    [MeaningOpcode.Fact, "e:remote", "prop:commands", 1842, r("txt:commands"), 2, 1, null],
    [MeaningOpcode.Fact, "e:remote", "prop:success-rate", 0.997, r("txt:success-rate"), 4, 1, null],
    [MeaningOpcode.Fact, "e:remote", "prop:p95", 3.8, r("txt:p95"), 2, 0, null],

    [MeaningOpcode.Relation, "e:acme", "e:release", "rel:owns", null],
    [MeaningOpcode.Relation, "e:brightline", "e:incident", "rel:affects", null],
    [MeaningOpcode.Relation, "e:release", "e:remote", "rel:depends", null],
    [MeaningOpcode.Relation, "e:incident", "e:remote", "rel:depends", null],

    [MeaningOpcode.Action, "a:approve", MeaningActionKind.Toggle, r("txt:approve"), "e:release", "prop:approved", false, 2, r("txt:approve-description"), "op:deployment.approve"],
    [MeaningOpcode.Action, "a:ring", MeaningActionKind.Choice, r("txt:set-ring"), "e:release", "prop:ring", ["pilot", [[r("txt:ring-pilot"), "pilot"], [r("txt:ring-broad"), "broad"], [r("txt:ring-production"), "production"]]], 0, null, "op:deployment.ring"],
    [MeaningOpcode.Action, "a:note", MeaningActionKind.Text, r("txt:add-note"), "e:release", "prop:note", ["Pilot checks are clean. Waiting for production approval.", r("txt:note-placeholder"), true], 0, null, "op:deployment.note"],
    [MeaningOpcode.Action, "a:retry", MeaningActionKind.Emit, r("txt:retry"), "e:incident", null, ["e:incident"], 1, r("txt:retry-description"), "op:incident.retry"],
    [MeaningOpcode.Action, "a:delete", MeaningActionKind.Emit, r("txt:delete"), "e:incident", null, ["e:incident"], 4, null, "op:incident.delete"],

    [MeaningOpcode.Signal, "s:release-approval", "e:release", 0.82, r("txt:approval-signal"), 0.99, r("txt:policy-engine"), "2026-07-31T21:30:00.000Z"],
    [MeaningOpcode.Signal, "s:incident-overdue", "e:incident", 0.91, r("txt:incident-signal"), 0.96, r("txt:monitor"), "2026-07-31T21:42:00.000Z"],
    [MeaningOpcode.Evidence, "ev:release-health", "e:release", r("txt:monitor"), r("txt:release-evidence"), 0.99, "2026-07-31T21:20:00.000Z"],
    [MeaningOpcode.Evidence, "ev:incident-support", "e:incident", r("txt:policy-engine"), r("txt:incident-evidence"), 0.93, "2026-07-31T21:10:00.000Z"],

    [MeaningOpcode.Permission, "a:approve", 2, r("txt:approve-policy")],
    [MeaningOpcode.Permission, "a:retry", 0, r("txt:retry-policy")],
    [MeaningOpcode.Permission, "a:delete", 1, r("txt:delete-policy")],
  ],
];
